### ISSUE TITLE
Bigquery schema evolution does not work when using batch mode.

### ISSUE THREAD

**Issue by hansh0801** [confluentinc/kafka-connect-bigquery#242]
I am currently testing loading data into bigquery using batch mode.

When using bigquery batch loading mode, even if avro schema evolution occurs, bigquery schema evolution does not occur. and  log message is not appeared.

If I turn off enableBatchLoad and restart the connector, bigquery schema evolution works normally.

```
[INFO] 2022-09-23 10:51:51,149 [pool-54-thread-1] com.wepay.kafka.connect.bigquery.SchemaManager updateSchema - Attempting to update table ``.`BIGQUERY_TEST_AVRO` with schema Schema{fields =[Field{name= type=STRING, mode=NULLABLE, description=null, policyTags=null, maxLength=null, scale=null, precision=null}, Field{name=EVENT_TYPE, type=STRING, ..... .....
```

What options do I need to change for schema update while using bigquery batch load mode?

connector config
```
   configs:
     topics: "BIGQUERY_TEST_AVRO"
     sanitizeTopics: "true"
     autoCreateTables: "true"
     queueSize: "500"
     bigQueryRetry: "10"
     bigQueryRetryWait: "1000"
     autoUpdateSchemas: "true"
     allowSchemaUnionization: "true"
     allowNewBigQueryFields: "true"
     allowBigQueryRequiredFieldRelaxation: "true"
     schemaRetriever: "com.wepay.kafka.connect.bigquery.retrieve.IdentitySchemaRetriever"
     project: "project"
     defaultDataset: "dataset"
     keyfile: "keyfile"
     includeKafkaData: "true"
     enableBatchLoad: "BIGQUERY_TEST_AVRO"
     batchLoadIntervalSec: "10"
     gcsBucketName: "bucket"
```
