### ISSUE TITLE
JSON data type is not working

### ISSUE THREAD

**Issue by kgw7401** [confluentinc/kafka-connect-bigquery#370]
I am currently trying to load data using the BigQuery Sink Connector. I have defined the schema for the data I want to load into BigQuery, and the schema looks like the following:
```
[
  {
    "name": "device_id",
    "type": "STRING",
    "mode": "REQUIRED"
  },
  {
    "name": "version",
    "type": "STRING",
    "mode": "NULLABLE"
  },
  {
    "name": "device",
    "type": "RECORD",
    "mode": "NULLABLE",
    "fields": [
      {
        "name": "category",
        "type": "STRING",
        "mode": "NULLABLE"
      },
      {
        "name": "os",
        "type": "STRING",
        "mode": "NULLABLE"
      }
    ]
  },
  {
    "name": "parameters",
    "type": "JSON",
    "mode": "NULLABLE"
  }
]
```

The issue I’m facing is that when loading a field with the JSON data type in BigQuery, the field is recognized as a RECORD type, causing the operation to fail. The error message I’m encountering is as follows:
```
(location parameters, reason: invalid): This field: parameters is not a record.
```

Additionally, the Connector YAML is as follows:
```
---
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
name: bigquery-event-log-sink-connector
spec:
  taskMax: 1
  configs:
    defaultDataset: event_log
    project: <project_name>
    topics: <topic_name>
    autoCreateTables: "false"
    autoUpdateSchemas: "false"
    bigQueryPartitionDecorator: "false"
    timestampPartitionFieldName: timestamp
    topic2TableMap: <topic_name>:<table_name>
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: "false"
    transforms: "TimestampIntCast,TimestampConverter"
    transforms.TimestampIntCast.type: org.apache.kafka.connect.transforms.Cast$Value
    transforms.TimestampIntCast.spec: timestamp:int64
    transforms.TimestampConverter.type: org.apache.kafka.connect.transforms.TimestampConverter$Value
    transforms.TimestampConverter.target.type: string
    transforms.TimestampConverter.field: timestamp
    transforms.TimestampConverter.format: "yyyy-MM-dd HH:mm:ss"
```

help me with this issue pls
