### ISSUE TITLE
java.lang.NoClassDefFoundError: com/google/cloud/bigquery/BigQuery

### ISSUE THREAD

**Issue by ahmedjami** [confluentinc/kafka-connect-bigquery#56]
Hello,
I am trying to run kafka-connect-bigquery and getting the following error:
```
2020-11-19 21:49:29,361] ERROR Stopping due to error (org.apache.kafka.connect.cli.ConnectDistributed)
connect_1         | java.lang.NoClassDefFoundError: com/google/cloud/bigquery/BigQuery
connect_1         |     at java.lang.Class.getDeclaredConstructors0(Native Method)
connect_1         |     at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
connect_1         |     at java.lang.Class.getConstructor0(Class.java:3075)
connect_1         |     at java.lang.Class.newInstance(Class.java:412)
connect_1         |     at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.versionFor(DelegatingClassLoader.java:380)
connect_1         |     at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.getPluginDesc(DelegatingClassLoader.java:350)
connect_1         |     at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanPluginPath(DelegatingClassLoader.java:330)

```
Using the following versions:
  
` image: confluentinc/cp-kafka:5.3.1`
 ` FROM confluentinc/cp-kafka-connect:5.4.3`

Any idea please ?
thanks

**Comment by C0urante** [comment]
@ahmedjami how are you starting the connector? And how are you adding it to the Docker image?

**Comment by ahmedjami** [comment]
Hi @C0urante,

I'm building the Connector from docker as described below:
```
FROM confluentinc/cp-kafka-connect:5.4.3
RUN mkdir /usr/kafka-connect-bq/
COPY kcbq-connector-1.6.5.jar /usr/kafka-connect-bq/
```
Then I'm starting all the components (zookeeper, cp-kafka, kafka-connector and schema-registry)  with docker-compose:

```

version: '2.1'

services:
  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo1:2888:3888
    volumes:
      - ./helenus-dev/zoo1/data:/data
      - ./helenus-dev/zoo1/datalog:/datalog

  kafka2:
    image: confluentinc/cp-kafka:5.3.1
    hostname: kafka2
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    volumes:
      - ./helenus-dev/kafka2/data:/var/lib/kafka/data
    depends_on:
      - zoo1
  schemaregistry:
    image: confluentinc/cp-schema-registry
    hostname: schemaregistry
    ports:
      - "8081:8081"
    environment:
      - "SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zoo1:2181"
      - "SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL=PLAINTEXT"
      - "SCHEMA_REGISTRY_LISTENERS=http://schemaregistry:8081, http://localhost:8081"
      - "SCHEMA_REGISTRY_HOST_NAME=schemaregistry"
      - "SCHEMA_REGISTRY_DEBUG=true"
    volumes:
      - ./helenus-dev/schemaregistry/data:/var/lib/
    depends_on:
      - kafka2
  connect:
    build:
      context: .
      dockerfile: Dockerfile_kafkaconnect
    depends_on:
      - zoo1
      - kafka2
      - schemaregistry
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "kafka2:9092"
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schemaregistry:8081'
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: 'http://schemaregistry:8081'
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "1"
      CONNECT_PLUGIN_PATH: '/usr/kafka-connect-bq'

```
When it's started, kafka-connect works well until reaching the stage where it will discover and load the connector and stop with the following error:

```
NFO Loading plugin from: /usr/kafka-connect-bq/kcbq-connector-1.6.5.jar (org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader)
connect_1         | [2020-11-19 21:49:29,361] ERROR Stopping due to error (org.apache.kafka.connect.cli.ConnectDistributed)
connect_1         | java.lang.NoClassDefFoundError: com/google/cloud/bigquery/BigQuery

```
