### ISSUE TITLE
Array of strings isn't properly casted as repeated field in big query

### ISSUE THREAD

**Issue by HarenBroog** [confluentinc/kafka-connect-bigquery#96]
**version:**  `confluent-hub install wepay/kafka-connect-bigquery:2.1.0`

Hi!

There is a problem with casting record with given schema:
```json
{
      "name": "my_array",
      "type": {
        "items": "string",
        "type": "array"
      }
}
```

During table creation in big query, connector sets this field schema as `String` 
![image](https://user-images.githubusercontent.com/6953951/113156947-be190000-923a-11eb-9894-42e4125874c3.png). 

Importing rows ends with error:
```
[row index 495]: invalid: Array specified for non-repeated field.
```
I think schema for that field, should be created with "repeated" option in BigQuery.

**Comment by C0urante** [comment]
It looks like this _should_ be covered by existing code:

https://github.com/confluentinc/kafka-connect-bigquery/blob/v2.1.0/kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/convert/BigQuerySchemaConverter.java#L165-L167

https://github.com/confluentinc/kafka-connect-bigquery/blob/v2.1.0/kcbq-connector/src/main/java/com/wepay/kafka/connect/bigquery/convert/BigQuerySchemaConverter.java#L223

And we have a test case that covers arrays of floats:

https://github.com/confluentinc/kafka-connect-bigquery/blob/v2.1.0/kcbq-connector/src/test/resources/integration_test_cases/matryoshka-dolls/schema.json#L10-L15

@HarenBroog Could you provide your connector config and Connect worker config (with any sensitive details such as credentials removed)? Once I have those I'll try to reproduce and hopefully we can move forward from there.

**Comment by HarenBroog** [comment]
Yep, I saw tests for this one, thus it's very strange.

Connector:
```json
{
      "name": "big-query-sink-connector-my_topic",
      "config": {
        "connector.class": "com.wepay.kafka.connect.bigquery.BigQuerySinkConnector",
        "tasks.max": "2",
        "topics": "my_topic",
        "sanitizeTopics": true,
        "autoCreateTables": true,
        "autoUpdateSchemas": true,
        "schemaRetriever": "com.wepay.kafka.connect.bigquery.retrieve.IdentitySchemaRetriever",
        "bufferSize": "100000",
        "maxWriteSize": "10000",
        "tableWriteWait": "1000",
        "project": "my_project",
        "defaultDataset": "dataset",
        "keyfile": "/var/keys/big-query-key.json",
        "bigQueryPartitionDecorator": false,
        "bigQueryMessageTimePartitioning": false,
        "timestampPartitionFieldName": "partition_key",
        "errors.deadletterqueue.topic.name": "my_topic",
        "errors.deadletterqueue.topic.replication.factor": 3,
        "allowNewBigQueryFields": true,
        "allowBigQueryRequiredFieldRelaxation": true,
        "allowSchemaUnionization": true,
        "includeKafkaData": true,
      }
    }
```

kafka-connect is set up with config map like:
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka-connect-config
  namespace: kafka-connect
data:
  CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
  CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components"
  BOOTSTRAP_SERVERS: "kafka.servers:9092"
  BASIC_AUTH_CREDENTIALS_SOURCE: "USER_INFO"
  SCHEMA_REGISTRY_URL: https://registry_url.com
  CONNECT_BOOTSTRAP_SERVERS: "kafka.servers:9092"
  CONNECT_REST_PORT: "8083"
  CONNECT_GROUP_ID: "my-group"
  CONNECT_CONFIG_STORAGE_TOPIC: "my-group-configs"
  CONNECT_OFFSET_STORAGE_TOPIC: "my-group-offsets"
  CONNECT_STATUS_STORAGE_TOPIC: "my-group-status"
  CONNECT_REPLICATION_FACTOR: "3"
  CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "3"
  CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "3"
  CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "3"
  CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
  CONNECT_LOG4J_LOGGERS: "org.reflections=ERROR"
  # CLASSPATH required due to CC-2422
  CLASSPATH: "/usr/share/java/monitoring-interceptors/monitoring-interceptors-6.1.0.jar"
  # Converters
  CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
  CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
  CONNECT_VALUE_CONVERTER_ENHANCED_AVRO_SCHEMA_SUPPORT: "true"
  CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "true"
  CONNECT_VALUE_CONVERTER_VALUE_SUBJECT_NAME_STRATEGY: "io.confluent.kafka.serializers.subject.RecordNameStrategy"
  CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: https://registry_url.com
  CONNECT_VALUE_CONVERTER_BASIC_AUTH_CREDENTIALS_SOURCE: USER_INFO
  # Connect worker
  CONNECT_SECURITY_PROTOCOL: "SASL_SSL"
  CONNECT_SASL_MECHANISM: "PLAIN"
  # Connect producer
  CONNECT_PRODUCER_SECURITY_PROTOCOL: "SASL_SSL"
  CONNECT_PRODUCER_SASL_MECHANISM: "PLAIN"
  CONNECT_PRODUCER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor"
  CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL: "SASL_SSL"
  CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: "PLAIN"
  # Connect consumer
  CONNECT_CONSUMER_SECURITY_PROTOCOL: "SASL_SSL"
  CONNECT_CONSUMER_SASL_MECHANISM: "PLAIN"
  CONNECT_CONSUMER_INTERCEPTOR_CLASSES: "io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor"
  CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SECURITY_PROTOCOL: "SASL_SSL"
  CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_MECHANISM: "PLAIN"
```

Dockerfile:
```dockerfile
FROM confluentinc/cp-server-connect-base:6.1.0

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"

RUN confluent-hub install --no-prompt debezium/debezium-connector-postgresql:1.4.0
RUN confluent-hub install --no-prompt wepay/kafka-connect-bigquery:2.1.0
RUN confluent-hub install --no-prompt confluentinc/connect-transforms:latest
```
